// <auto-generated />
using MealManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260405165442_Change-Schema-Name-And-Remove-DisplayOrder-Column")]
    partial class ChangeSchemaNameAndRemoveDisplayOrderColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealManagement.Domain.Entities.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasOptionGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Meals", "Menu");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.MealOptionGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MealId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("MealId", "Name")
                        .IsUnique();

                    b.ToTable("MealOptionGroups", "Menu");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.OptionGroupItems", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPobular")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OptionGroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId", "Name")
                        .IsUnique();

                    b.ToTable("OptionGroupItems", "Menu");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.MealOptionGroup", b =>
                {
                    b.HasOne("MealManagement.Domain.Entities.Meal", "Meal")
                        .WithMany("MealOptionGroups")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.OptionGroupItems", b =>
                {
                    b.HasOne("MealManagement.Domain.Entities.MealOptionGroup", "OptionGroup")
                        .WithMany("Items")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealOptionGroups");
                });

            modelBuilder.Entity("MealManagement.Domain.Entities.MealOptionGroup", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
